### ISSUE TITLE
Baseline datacube at classis level

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/occ-cube-alien#11]
While discussing about occurrence indicators https://github.com/trias-project/indicators/issues/49 @timadriaens suggests to calculate baseline based on phylum instead of phylum as 
> this is a widely used procedure to make distribution models of alien species. [Tim Adrieans]

**Comment by timadriaens** [comment]
Sorry, I meant **classis** level (birds, reptiles, mammals, fish...) as this is probably more linked to sampling method/effort

**Comment by damianooldoni** [comment]
No problem. I have just modified title. We will see what happens but theoretically nothing strange should happen, just some more lines in the final baseline datacube, as there are more classis than kingdoms.

**Comment by damianooldoni** [comment]
Solved by #12
