### ISSUE TITLE
eea grid code

### ISSUE THREAD

**Issue by ToonVanDaele** [trias-project/occ-cube-alien#13]
Some 'eea_cell_code' have negative values ex. 1kmE3370N-2322, 1kmE-412N6010, 1kmE-410N6010

**Comment by damianooldoni** [comment]
Thanks @ToonVanDaele to discover this issue. I will check it.

**Comment by damianooldoni** [comment]
I think I found the problem: nothing to do with grid cell code assessment, but with occurrences.
In the Belgian cube, `data/processed/cube_belgium.tsv`, I found one negative longitude:

year | eea_cell_code | taxonKey | n | min_coord_uncertainty
-- | -- | -- | -- | --
1967 | 1kmE7589N-1127 | 2706406 | 1 | 1000

Searching on GBIF for this taxon key, in country = Belgium and year = 1967, I found one occurrence as expected. What I didn't expected was the location of it: Ethiopia! See here:
https://www.gbif.org/occurrence/1301495196
Published in [A global database for the distributions of crop wild relatives](https://www.gbif.org/dataset/07044577-bd82-4089-9f3a-f4a9d2170b2e).

Other two examples, this time from the aggregated datacube at class level, `cube_belgium_baseline.tsv`:

year | eea_cell_code | taxonKey | n | min_coord_uncertainty
-- | -- | -- | -- | --
1972 | 1kmE-412N6010 | 220 | 1 | 1000
1979 | 1kmE3837N-310 | 359 | 1 | 1000

These are situated in Canada and Algeria respectively: 
https://www.gbif.org/occurrence/1840538639
https://www.gbif.org/occurrence/1436974472

Published respectively in [Meise Botanic Garden Herbarium (BR)](https://www.gbif.org/dataset/b740eaa0-0679-41dc-acb7-990d562dfa37) and [RBINS DaRWIN](https://www.gbif.org/dataset/8138eb72-f762-11e1-a439-00145eb45e9a).

Again, occurrences labelled with issue `Country coordinate mismatch`.
So, we should also filter out occurrences with issue `Country coordinate mismatch`. I am solving it in branch [Remove-occs-with-country_code_mismatch_issue](https://github.com/trias-project/occ-processing/tree/Remove-occs-with-country_code_mismatch_issue).

**Comment by qgroom** [comment]
@matdillen could you fix the coordinate mismatch in https://www.gbif.org/occurrence/1840538639 ?
You only need to fix it in BgBase and the correction will propagate when we next do an upload.

**Comment by damianooldoni** [comment]
Nice you are going to improve the Meise dataset :+1: 
@matdillen: I see 61 occurrences sharing this issue. Maybe you can solve them all?
Here the link to these occurrences:
https://www.gbif.org/occurrence/search?dataset_key=b740eaa0-0679-41dc-acb7-990d562dfa37&issue=COUNTRY_COORDINATE_MISMATCH

**Comment by qgroom** [comment]
@matdillen if you do want to get them all fixed it might be best to ask Nuno (via Anne). It will save you time and Nuno is very knowledgeable with BgBase and georeferencing.

**Comment by damianooldoni** [comment]
@ToonVanDaele : issue is solved by #14. New datacubes have been generated and are available on `master`. If everything is ok,close this issue.
@qgroom: about assigning right coordinates to the 61 occurrences from Meise Erbarium dataset, maybe you could open a new issue on Meise's related repo, if exists.

**Comment by matdillen** [comment]
@damianooldoni A few of those 61 are now fixed and will be published with the next GBIF update. This includes a few Belgian specimens from Dinant apparently georeferenced erroneously to Lac Dinant in Canada.

Most of these 61 are border cases, however, where we can't be sure whether the country is incorrect or the coordinates are not accurate enough.

**Comment by damianooldoni** [comment]
Thanks @matdillen . 
This can be tackled while pre-processing data while working on indicator or risk-mapping. 
As this issue is actually an issue of published data on GBIF, I close this issue here.
