### ISSUE TITLE
Save output files as csv instead of tsv

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/occ-cube-alien#21]
See https://github.com/trias-project/occ-cube/issues/3

**Comment by damianooldoni** [comment]
Maybe saving them as semicolon separated files? Then, we reduce problems in column `includes` of `*_info.csv` which contains scientific names. Scientific names contain sometimes commas a well...

**Comment by peterdesmet** [comment]
Can easily be tackled by "quoting" content. Should happen automatically when exporting to csv normally.

**Comment by damianooldoni** [comment]
I check it in occ-cube output.

**Comment by damianooldoni** [comment]
output is saved as csv. Issue solved.
