### ISSUE TITLE
Discard occurrences with unverified identificationVerificationStatus

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/occ-cube-alien#24]
Based on issue https://github.com/trias-project/indicators/issues/84:

1. Add column `identificationVerificationStatus` to the `cols_to_use` (https://github.com/trias-project/occ-cube-alien/blob/master/src/belgium/2_create_db.Rmd#L183-L193)
2. Discard occurrences with `identificationVerificationStatus = "unverified"`. This is very similar to what we already do for `occurrenceStatus` (https://github.com/trias-project/occ-cube-alien/blob/master/src/belgium/2_create_db.Rmd#L234-L241)

Apply these changes in both pipelines (BE and modelling taxa at EU level).

**Comment by damianooldoni** [comment]
As mentioned by @amyjsdavis in https://github.com/trias-project/indicators/issues/84#issuecomment-646684946 we have more values of field `identificationVerificationStatus` to filter out. While making the European occurrence cube I found observations with the following values:
- `unverified`,
- `unvalidated`,
- `not able to validate`
- `control could not be conclusive due to insufficient knowledge`

After briefing with @amyjsdavis, we decided to remove them.

**Comment by damianooldoni** [comment]
While making occurrence cube for risk assessment species as defined in [references/modelling_species.tsv](https://raw.githubusercontent.com/trias-project/occ-cube-alien/b22225d4eddb3bc6916f387c5a0d6dac3a38a90e/references/modelling_species.tsv), I found some other suspect values which I think we should include in the list of values to discard:

- `Unconfirmed`
- `Unconfirmed - not reviewed`
- `Unconfirmed - plausible`
- `Validation requested`

@qgroom, @amyjsdavis: what do you think about it?

**Comment by qgroom** [comment]
I would certainly include "Unconfirmed - plausible"

I would perhaps exclude the others. There are better ways to make this decision, but they are not so straightforward.

**Comment by damianooldoni** [comment]
Thanks @qgroom. Yes, `Unconfirmed - plausible` can be left. I agree.

Up to now it seems this field is free: it would be much better with a specific dictionary. For example, unverified and unconfirmed, I think could be surely merged.

**Comment by damianooldoni** [comment]
Done. I will close this issue again until new values to discard will be found.
