### ISSUE TITLE
set seed

### ISSUE THREAD

**Issue by amyjsdavis** [trias-project/occ-cube-alien#30]
@damianooldoni . I have a suggestion: If you would like to be able to obtain the exact the same random allocation of occurrences each time your run the occurrence cube script,  you should set the seed (e.g. set.seed(678).  For example, I would set the seed in the first line of code for {r assign_pts_in_circle_occs_eu} in the 2_assign_grid.Rmd.   This is useful if you want to control the variation among different cubes and to have an exactly reproducible cube.

**Comment by damianooldoni** [comment]
Thanks, @amyjsdavis . This can be useful indeed and it could be mentioned while speaking about FAIR principles.

**Comment by PietrH** [comment]
I think it's a great idea, perhaps it's possible to log the seed for every run so the analysis can be repeated even if the seed was not set manually.

**Comment by damianooldoni** [comment]
This is done both for EU cube and BE cube.
