### ISSUE TITLE
Celastrus : GBIF code changed or inaccurate ?

### ISSUE THREAD

**Issue by b-dhondt** [trias-project/occ-cube-alien#39]
@damianooldoni -- I accidently noticed that the GBIF code of [_Celastrus orbiculatus_ (8104460)](https://www.gbif.org/species/8104460) is deleted as of March 2021. I assume the new GBIF code is [3169169](https://www.gbif.org/species/3169169). I assume this change of codes is also due for the occurrence cube.

**Comment by damianooldoni** [comment]
Yes, indeed. The taxon keys in the cube can get outdated if such the taxon keys in the GBIF Backbone change.
As I told you last week, I built a [tool](https://github.com/riparias/taxon-keys-early-alert) within LIFE RIPARIAS project to get promptly notified by such changes. This tool could be implemented for any checklist (containing taxa pointing to taxa of the GBIF Backbone) or even for the entire GBIF Backbone.

Ideally, a new occurrence cube should be generated if something like that occurs.
